
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  application:
    name: PRODUCT-SERVICE

server:
  port: 8071


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka